sonar.projectKey=aupp-lms-backend
sonar.projectName=AUPP LMS Backend
sonar.projectVersion=1.0
sonar.sources=app
sonar.sourceEncoding=UTF-8

# Example for Python
sonar.python.version=3.12

# Optional exclusions
sonar.exclusions=**/__pycache__/**,**/tests/**