[jenkins]
jenkins ansible_host=54.81.182.145 ansible_user=ubuntu ansible_ssh_private_key_file=./secrets/ssh/devop-final-key.pem ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[sonarqube]
sonarqube ansible_host=54.80.56.208 ansible_user=ubuntu ansible_ssh_private_key_file=./secrets/ssh/devop-final-key.pem ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
