[jenkins]
jenkins ansible_host=54.152.61.181 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[sonarqube]
sonarqube ansible_host=18.234.26.44 ansible_user=ubuntu ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3